// AUTO-GENERATED from paintings.json
window.PAINTINGS_DATA = [
    {
        "id": "last-light",
        "title": "Last Light",
        "image": "images/Last Light.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "landscape",
        "status": "available",
        "featured": true,
        "orientation": "landscape",
        "printAvailable": false,
        "framed": true,
        "price": 495
    },
    {
        "id": "curious",
        "title": "Curious",
        "image": "images/PXL_20260527_174224267.NIGHT~2 (3)bearcub.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "landscape",
        "status": "available",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 495
    },
    {
        "id": "painted-shore",
        "title": "Painted Shore",
        "image": "images/PXL_20260516_174059562 (2)LakeMcDonaldBrightRocks.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "landscape",
        "status": "available",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 495
    },
    {
        "id": "still-water",
        "title": "Still Water",
        "image": "images/PXL_20260519_121453165LakeMcDonaldSubmergedRocks.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 310
    },
    {
        "id": "wild-goose-island",
        "title": "Wild Goose Island",
        "image": "images/IMG_20260208_135907950 (1).JPG",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 310
    },
    {
        "id": "the-catch",
        "title": "The Catch",
        "image": "images/IMG_20250824_123114634.JPG",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "the-long-way-home",
        "title": "The Long Way Home",
        "image": "images/IMG_20260316_184424103.JPG",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "winter-watch",
        "title": "Winter Watch",
        "image": "images/IMG_20251230_163413411 (1).JPG",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "landscape",
        "status": "available",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 495
    },
    {
        "id": "emergence",
        "title": "Emergence",
        "image": "images/PXL_20260504_222622804.jpg",
        "medium": "Oil on canvas",
        "size": "12 × 24 in.",
        "category": "landscape",
        "status": "available",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 360
    },
    {
        "id": "autumn-sentinel",
        "title": "Autumn Sentinel",
        "image": "images/Autumn Sentinal.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "landscape",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "glacier-melt",
        "title": "Glacier Melt",
        "image": "images/IMG_20260201_202503122 (2).JPG",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 310
    },
    {
        "id": "may-flowers",
        "title": "May Flowers",
        "image": "images/PXL_20260508_134953911 (1).jpg",
        "medium": "Oil on canvas panel",
        "size": "5 × 7 in.",
        "category": "landscape",
        "status": "available",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "alpine-meadow",
        "title": "Alpine Meadow",
        "image": "images/PXL_20260527_175720751~2AlpineMeadow.jpg",
        "medium": "Oil on canvas panel",
        "size": "8 × 12 in.",
        "category": "landscape",
        "status": "available",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true,
        "price": 175
    },
    {
        "id": "loose-cougar",
        "title": "Loose Cougar",
        "image": "images/PXL_20260527_175747536~2loose cougar.jpg",
        "medium": "Oil on canvas panel",
        "size": "5 × 7 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "coastal-reckoning",
        "title": "Coastal Reckoning",
        "image": "images/Coastal Reckoning.jpg",
        "medium": "Oil on canvas",
        "size": "48 × 60 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "meadow-crossing",
        "title": "Meadow Crossing",
        "image": "images/IMG_20260309_220312355.JPG",
        "medium": "Oil on canvas",
        "size": "30 × 40 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "avalanche-gorge",
        "title": "Avalanche Gorge",
        "image": "images/Hero Page.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "moose-majesty",
        "title": "Moose Majesty",
        "image": "images/moose-majesty.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "morning-launch",
        "title": "Morning Launch",
        "image": "images/Untitled_Artworklakeadjusted.jpg",
        "medium": "Oil on canvas panel",
        "size": "9 × 12 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "landscape",
        "printAvailable": true
    },
    {
        "id": "the-lookout",
        "title": "The Lookout",
        "image": "images/IMG_20260216_082037013.JPG",
        "medium": "Oil on canvas",
        "size": "16 × 20 in.",
        "category": "pet-portraits",
        "status": "commissioned",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "pretzel",
        "title": "Pretzel",
        "image": "images/IMG_20260309_124039381.JPG",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "pet-portraits",
        "status": "commissioned",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "zip",
        "title": "Zip",
        "image": "images/PXL_20260501_160056437.MP.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "pet-portraits",
        "status": "commissioned",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "watcher-bear",
        "title": "Watcher Bear",
        "image": "images/watcher bear.jpg",
        "medium": "Oil on canvas panel",
        "size": "5 × 7 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "great-northern",
        "title": "Great Northern",
        "image": "images/great northern.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "moose-river",
        "title": "Moose River",
        "image": "images/Moose River.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "sold",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false
    },
    {
        "id": "gray-wolf",
        "title": "Gray Wolf",
        "image": "images/Gray Wolf.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "bison-in-wheat",
        "title": "Bison in Wheat",
        "image": "images/Bison in Wheat.jpg",
        "medium": "Oil on canvas",
        "size": "11 × 14 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "the-itch",
        "title": "The Itch",
        "image": "images/The Itch.jpg",
        "medium": "Oil on canvas panel",
        "size": "9 × 12 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "story-time-chief-mountain",
        "title": "Story Time at Chief Mountain",
        "image": "images/Blackfeet camp and Chief Mountain.jpg",
        "medium": "Oil on panel",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "landscape",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "spirit-eye",
        "title": "Spirit Eye",
        "image": "images/Spirit Eye.jpg",
        "medium": "Oil on canvas",
        "size": "8 × 10 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "wolf-in-aspen-summer",
        "title": "Wolf in Aspen — Summer",
        "image": "images/Wolf in Aspen Summer.jpg",
        "medium": "Oil on panel",
        "size": "9 × 11 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "wolf-in-aspen-fall",
        "title": "Wolf in Aspen — Fall",
        "image": "images/Wolf in Aspen Fall.jpg",
        "medium": "Oil on panel",
        "size": "9 × 11 in.",
        "category": "wildlife",
        "status": "available-at-montana-fur-traders",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": true
    },
    {
        "id": "athena",
        "title": "Athena",
        "image": "images/IMG_20260731_193249.jpg",
        "medium": "Oil on canvas",
        "size": "18 × 24 in.",
        "category": "pet-portraits",
        "status": "commissioned",
        "featured": true,
        "orientation": "portrait",
        "printAvailable": false,
        "framed": false
    },
    {
        "id": "letting-go",
        "title": "Letting Go",
        "image": "images/Letting Go.jpg",
        "medium": "Oil on canvas panel",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": true
    },
    {
        "id": "breathe",
        "title": "Breathe",
        "image": "images/Breathe.jpg",
        "medium": "Oil on canvas panel",
        "size": "11 × 14 in.",
        "category": "landscape",
        "status": "private-collection",
        "featured": false,
        "orientation": "portrait",
        "printAvailable": true
    }
];
